import { Html, RoundedBox } from "@react-three/drei";

function FallbackModel({ id, color }) {
  const material = { color, metalness: 0.55, roughness: 0.3 };
  if (id === "ram" || id === "memory") return <group rotation={[0, 0, Math.PI / 2]}><RoundedBox args={[5.8, 1.25, 0.22]} radius={0.08} smoothness={4}><meshStandardMaterial {...material} color="#166534" /></RoundedBox>{[-2, -1, 0, 1, 2].map((x) => <mesh key={x} position={[x, 0, 0.16]}><boxGeometry args={[0.62, 0.8, 0.08]} /><meshStandardMaterial color="#d4a72c" metalness={0.7} /></mesh>)}<mesh position={[0, -0.66, 0]}><boxGeometry args={[5.8, 0.08, 0.3]} /><meshStandardMaterial color="#d4a72c" /></mesh></group>;
  if (id === "gpu") return <group rotation={[0, 0, Math.PI / 2]}><RoundedBox args={[4.8, 2.2, 0.28]} radius={0.12} smoothness={4}><meshStandardMaterial {...material} color="#164e63" /></RoundedBox><mesh position={[0, 0, 0.2]}><cylinderGeometry args={[0.72, 0.72, 0.2, 32]} /><meshStandardMaterial color="#94a3b8" metalness={0.8} /></mesh><mesh position={[0, 0, 0.32]} rotation={[Math.PI / 2, 0, 0]}><torusGeometry args={[0.5, 0.08, 12, 32]} /><meshStandardMaterial color="#0f172a" /></mesh></group>;
  if (id === "storage") return <group rotation={[0, 0, Math.PI / 2]}><RoundedBox args={[3.8, 1.5, 0.3]} radius={0.18} smoothness={4}><meshStandardMaterial {...material} color="#475569" /></RoundedBox><mesh position={[0, 0, 0.2]}><boxGeometry args={[1.8, 0.18, 0.05]} /><meshStandardMaterial color="#38bdf8" emissive="#0e7490" /></mesh></group>;
  if (id === "motherboard") return <group><RoundedBox args={[5.2, 0.3, 4.2]} radius={0.12} smoothness={4}><meshStandardMaterial {...material} color="#14532d" /></RoundedBox><mesh position={[-0.7, 0.32, 0.3]}><boxGeometry args={[1.7, 0.18, 1.7]} /><meshStandardMaterial color="#64748b" metalness={0.8} /></mesh>{[-1.8, -1.2, -0.6, 0, 0.6, 1.2].map((z) => <mesh key={z} position={[1.5, 0.32, z]}><boxGeometry args={[0.22, 0.12, 0.42]} /><meshStandardMaterial color="#d4a72c" /></mesh>)}</group>;
  if (id === "psu") return <group><RoundedBox args={[3.6, 2.2, 2.5]} radius={0.18} smoothness={4}><meshStandardMaterial {...material} color="#1e293b" /></RoundedBox><mesh position={[0, 0, 1.27]} rotation={[Math.PI / 2, 0, 0]}><cylinderGeometry args={[0.7, 0.7, 0.08, 32]} /><meshStandardMaterial color="#0f172a" /></mesh><mesh position={[0, 0, 1.32]} rotation={[Math.PI / 2, 0, 0]}><torusGeometry args={[0.55, 0.07, 12, 32]} /><meshStandardMaterial color="#94a3b8" /></mesh></group>;
  if (id === "network") return <group rotation={[0, 0, Math.PI / 2]}><RoundedBox args={[3.8, 1.4, 0.25]} radius={0.1} smoothness={4}><meshStandardMaterial {...material} color="#064e3b" /></RoundedBox>{[-1.1, 0, 1.1].map((x) => <mesh key={x} position={[x, 0, 0.2]}><boxGeometry args={[0.55, 0.55, 0.08]} /><meshStandardMaterial color="#22c55e" emissive="#166534" /></mesh>)}</group>;
  if (id === "cooling") return <group><mesh><cylinderGeometry args={[1.7, 1.7, 0.35, 32]} /><meshStandardMaterial color="#64748b" metalness={0.8} /></mesh><mesh rotation={[Math.PI / 2, 0, 0]}><torusGeometry args={[1.15, 0.1, 12, 32]} /><meshStandardMaterial color="#38bdf8" /></mesh></group>;
  if (id === "io-controller" || id === "dma" || id === "mmu") return <group><RoundedBox args={[2.8, 0.55, 2.2]} radius={0.15} smoothness={4}><meshStandardMaterial {...material} /></RoundedBox>{[-0.8, 0, 0.8].map((x) => <mesh key={x} position={[x, 0.38, 0]}><cylinderGeometry args={[0.12, 0.12, 0.3, 16]} /><meshStandardMaterial color="#fbbf24" /></mesh>)}</group>;
  return <group><RoundedBox args={[2.6, 0.65, 2.6]} radius={0.3} smoothness={5}><meshStandardMaterial {...material} /></RoundedBox><mesh position={[0, 0.38, 0]}><boxGeometry args={[1.5, 0.05, 1.5]} /><meshStandardMaterial color="#cbd5e1" metalness={0.8} /></mesh></group>;
}

export default function ComponentModel({ component, showLabel = true, labelPosition = [0, -2.7, 0] }) {
  return <group position={[0, 0, 0]} rotation={component.modelRotation || [0, 0, 0]}><group scale={component.modelScale || 1}><FallbackModel id={component.id} color={component.color} /></group>{showLabel && <Html position={labelPosition} center><div className="three-label active" style={{ borderColor: component.color }}>{component.name.toUpperCase()}</div></Html>}</group>;
}
